# Generated by Django 4.0.5 on 2022-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('tipo', models.CharField(choices=[('F', 'Disponible en fisico'), ('D', 'Disponible en Digital')], max_length=1, verbose_name='disponibilidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('link', models.CharField(default='hola', max_length=300, verbose_name='link')),
            ],
        ),
    ]
