# Generated by Django 4.0.5 on 2022-06-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numero_dex')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('tipo1', models.CharField(max_length=50, verbose_name='Tipo Principal')),
                ('tipo2', models.CharField(max_length=50, verbose_name='Tipo secundario')),
                ('peso', models.IntegerField(verbose_name='peso')),
                ('altura', models.IntegerField(verbose_name='altura')),
            ],
        ),
    ]
