# Generated by Django 4.0.5 on 2022-06-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo')),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='noticias')),
            ],
        ),
    ]
