# Generated by Django 4.0.5 on 2022-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_noticias', '0002_alter_noticias_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='cuerpo',
            field=models.CharField(max_length=800),
        ),
    ]
