# Generated by Django 4.0.5 on 2022-06-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_noticias', '0003_alter_noticias_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
