# Generated by Django 4.0.5 on 2022-06-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_noticias', '0004_alter_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='titulo'),
        ),
    ]
