# Generated by Django 4.0.5 on 2022-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_noticias', '0005_alter_noticias_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='link',
            field=models.CharField(default='hola', max_length=300, verbose_name='link'),
        ),
    ]
