# Generated by Django 4.0.5 on 2022-06-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_noticias', '0006_noticias_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='link',
            field=models.CharField(default='www.google.com', max_length=300, verbose_name='link'),
        ),
    ]
